apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicatset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
        app: my-nginx-pod
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: my-nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx
